// To parse this JSON data, do
//
//     final userModel = userModelFromJson(jsonString);
// ignore_for_file: overridden_fields, empty_catches, override_on_non_overriding_member
import 'dart:async';
import 'dart:convert';
import 'dart:developer';

import 'package:json_annotation/json_annotation.dart';
import 'package:xml/xml.dart';

import '../../../../../app/core/interfaces/entity_model.dart';
import '../entities/item.dart';

ItemModel itemModelFromJson(String str) => ItemModel.fromJson(json.decode(str));

ItemList itemListModelFromJson(String str) =>
    ItemList.fromJson(json.decode(str));

String itemModelToJson(ItemModel data) => json.encode(data.toJson());

class ItemList<T extends ItemModel> implements EntityModelList<T> {
  final List<T> items;

  ItemList({
    this.items = const [],
  });

  factory ItemList.fromStringJson(String strJson) =>
      ItemList.fromJson(json.decode(strJson));

  factory ItemList.fromJson(Map<String, dynamic> json) => ItemList(
        items: List<T>.from(json["items"].map((x) => ItemModel.fromJson(x))),
      );

  factory ItemList.fromEmpty() => ItemList(
        items: List<T>.from([].map((x) => ItemList.fromJson(x))),
      );

  Map<String, dynamic> toJson() => {
        "items": List<dynamic>.from(items.map((x) => x.toJson())),
      };

  @override
  EntityModelList<T> fromJson(Map<String, dynamic> json) {
    return ItemList.fromJson(json);
  }

  @override
  EntityModelList<T> fromStringJson(String strJson) {
    return ItemList.fromStringJson(strJson);
  }

  @override
  List<T> getList() => items;

  @override
  int get getTotal => getList().length;

  @override
  EntityModelList<T> add(T element) => fromList([element]);

  @override
  EntityModelList<T> fromList(List<T> list) {
    for (var element in list) {
      if (!items.contains(element)) items.add(element);
    }
    return this;
  }

  static Future<T> fromXmlServiceUrl<T>(
      String url,
      String parentTagName,
      Future<T> Function(XmlDocument doc, XmlElement el) process,
      Future<T> Function() onError) async {
    return EntityModelList.fromXmlServiceUrl(
        url, parentTagName, process, onError);
  }

  static Future<T> getJsonFromXMLUrl<T>(
      String url,
      Future<T> Function(XmlDocument result) process,
      Future<T> Function() onError) async {
    return EntityModelList.getJsonFromXMLUrl(url, process, onError);
  }
}

@JsonSerializable()
class ItemModel extends Item implements EntityModel {
  //method generated by wizard
  @override
  T cloneWith<T extends EntityModel>(T other) {
    return ItemModel.fromJson(other.toJson()) as T;
  }

  @override
  T fromJson<T extends EntityModel>(Map<String, dynamic> params) {
    return ItemModel.fromJson(params) as T;
  }

  List<Object?> get props => [];

  bool? get stringify => true;
  @override
  final String idItem;

  ItemModel({
    required this.idItem,
  }) : super(
          idItem: idItem,
        );

  factory ItemModel.fromJson(Map<String, dynamic> json) => ItemModel(
        idItem: json["id_item"],
      );

  factory ItemModel.fromXml(
          XmlElement element, ItemModel Function(XmlElement el) process) =>
      process(element);

  @override
  static T getValueFrom<T>(
    String key,
    Map<dynamic, dynamic> json,
    T defaultValue, {
    JsonReader<T>? reader,
  }) {
    return EntityModel.getValueFromJson<T>(
      key,
      json,
      defaultValue,
      reader: reader,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
        "id_item": idItem,
      };

  @override
  Map<String, String> getColumnNames() {
    return {"id_item": "ID"};
  }

  @override
  List<String> getColumnNamesList() {
    return getColumnNames().values.toList();
  }

  @override
  EntityModelList createModelListFrom(dynamic data) {
    try {
      if (data is Map) {
        return ItemList.fromJson(data as Map<String, dynamic>);
      }
      if (data is String) {
        return ItemList.fromStringJson(data);
      }
    } on Exception {
      log("Error al mapear el parámetro 'data'. Debe ser de tipo'Map<String, dynamic>' o String");
    }
    return ItemList.fromJson({});
  }

  @override
  Map<String, ColumnMetaModel> getColumnMetaModel() {
    //Map<String, String> colNames = getColumnNames();
    metaModel = metaModel ??
        {
          //TODO Declare here all ColumnMetaModel. you can use class implementation of class "DefaultColumnMetaModel".
        };
    int index = 0;
    metaModel!.forEach((key, value) {
      value.setColumnIndex(index++);
    });
    return metaModel!;
  }

  @override
  Map<String, String> getVisibleColumnNames() {
    Map<String, String> names = {};
    getMeta<String, ColumnMetaModel>("visible", true)
        .map<String, String>((key, value) {
      names.putIfAbsent(key, () => value.getColumnName());
      return MapEntry(key, value.getColumnName());
    });
    return names;
    // throw UnimplementedError();
  }

  StreamController<EntityModel> getController({
    void Function()? onListen,
    void Function()? onPause,
    void Function()? onResume,
    FutureOr<void> Function()? onCancel,
  }) {
    return EntityModel.getController(
        entity: this,
        onListen: onListen,
        onPause: onPause,
        onResume: onResume,
        onCancel: onCancel);
  }

  @override
  Map<K1, V1> getMeta<K1, V1>(String searchKey, dynamic searchValue) {
    final Map<K1, V1> result = {};
    getColumnMetaModel().map<K1, V1>((key, value) {
      MapEntry<K1, V1> el = MapEntry(value.getDataIndex() as K1, value as V1);
      if (value[searchKey] == searchValue) {
        result.putIfAbsent(value.getDataIndex() as K1, () {
          return value as V1;
        });
      }
      return el;
    });
    return result;
  }

  @override
  Map<String, ColumnMetaModel>? get getMetaModel => getColumnMetaModel();

  @override
  set setMetaModel(Map<String, ColumnMetaModel> newMetaModel) {
    metaModel = newMetaModel;
  }

  @override
  Map<String, ColumnMetaModel>? metaModel;

  @override
  Map<String, ColumnMetaModel> updateColumnMetaModel(
      String keySearch, dynamic valueSearch, dynamic newValue) {
    Map<String, ColumnMetaModel> tmp = getColumnMetaModel();
    getMeta<String, ColumnMetaModel>(keySearch, valueSearch)
        .map<String, ColumnMetaModel>((key, value) {
      tmp.putIfAbsent(key, () => value);
      return MapEntry(key, value);
    });
    return metaModel = tmp;
  }
}
