class InvoiceByClient {
   String? paymentServiceId;
   int? transactionId;
    String? amount;
    double? totalAmount;
   String? branch;
   String? invoiceEz;
   String? owner;
   String? metadata;
   String? period;
   String? transactionUuid;
    DateTime? transactionCreatedAt;
    int? transactionStatusCode;
   String? transactionStatus;
   String? last4;
   String? currency;
   String? transactionDescription;
   String? transactionDenom;
    int? transactionCode;
   String? merchantAlias;
   String? merchantAvatar;
    String? bankCode;
   String? username;
   String? privuse2;
   dynamic bankDebitDetail;
   String? fundingSourceUuid;
   String? clientId;
   String? transactionSignature;
   String? rc04;
   String? folio;
   String? route;
   String? month;
   String? year;
   String? charged;
   String? invoiceDate;
   String? discount;
   String? consumption;

  InvoiceByClient({
    required this.amount,
    required this.bankCode,
    required this.bankDebitDetail,
    required this.branch,
    required this.clientId,
    required this.currency,
    required this.fundingSourceUuid,
    required this.invoiceEz,
    required this.last4,
    required this.merchantAlias,
    required this.merchantAvatar,
    required this.metadata,
    required this.owner,
    required this.paymentServiceId,
    required this.period,
    required this.privuse2,
    required this.rc04,
    required this.totalAmount,
    required this.transactionCode,
    required this.transactionCreatedAt,
    required this.transactionDenom,
    required this.transactionDescription,
    required this.transactionId,
    required this.transactionSignature,
    required this.transactionStatus,
    required this.transactionStatusCode,
    required this.transactionUuid,
    required this.username,
    required this.folio,
    required this.route,
    required this.month,
    required this.year,
    required this.charged,
    required this.invoiceDate,
    required this.discount,
    required this.consumption
  });

  
}