// To parse this JSON data, do
//
//     final userModel = userModelFromJson(jsonString);
// ignore_for_file: overridden_fields, empty_catches, override_on_non_overriding_member

import 'dart:async';
import 'dart:convert';
import 'dart:developer';

import 'package:xml/xml.dart';

import '../../../../../app/core/config/errors/exceptions.dart';
import '../../../../../app/core/interfaces/entity_model.dart';
import '../../../../../app/modules/home/domain/entities/user_notification.dart';
import '../../../../../app/modules/home/domain/models/user_notification_model.dart';
import '../entities/notify.dart';

NotifyList notifyListModelFromJson(String str) =>
    NotifyList.fromJson(json.decode(str));

NotifyModel notifyModelFromJson(String str) =>
    NotifyModel.fromJson(json.decode(str));

String notifyModelToJson(NotifyModel data) => json.encode(data.toJson());

class NotifyList<T extends NotifyModel> implements EntityModelList<T> {
  final List<T> notifys;

  NotifyList({
    required this.notifys,
  });

  factory NotifyList.fromJson(Map<String, dynamic> json) => NotifyList(
        notifys: json.isNotEmpty
            ? List<T>.from(json["notifys"].map((x) => NotifyModel.fromJson(x)))
            : [],
      );

  factory NotifyList.fromStringJson(String strJson) =>
      NotifyList.fromJson(json.decode(strJson));

  @override
  int get getTotal => getList().length;

  @override
  EntityModelList<T> add(T element) => fromList([element]);

  @override
  EntityModelList<T> fromJson(Map<String, dynamic> json) {
    return NotifyList.fromJson(json);
  }

  @override
  EntityModelList<T> fromList(List<T> list) {
    for (var element in list) {
      if (!notifys.contains(element)) notifys.add(element);
    }
    return this;
  }

  @override
  EntityModelList<T> fromStringJson(String strJson) {
    return NotifyList.fromStringJson(strJson);
  }

  @override
  List<T> getList() => notifys;

  Map<String, dynamic> toJson() => {
        "notifys": List<dynamic>.from(notifys.map((x) => x.toJson())),
      };

  static Future<T> fromXmlServiceUrl<T>(
      String url,
      String parentTagName,
      Future<T> Function(XmlDocument doc, XmlElement el) process,
      Future<T> Function() onError) async {
    return EntityModelList.fromXmlServiceUrl(
        url, parentTagName, process, onError);
  }

  static Future<T> getJsonFromXMLUrl<T>(
      String url,
      Future<T> Function(XmlDocument result) process,
      Future<T> Function() onError) async {
    return EntityModelList.getJsonFromXMLUrl(url, process, onError);
  }
}

class NotifyModel extends Notify implements EntityModel {
  @override
  String id;

  @override
  String idNotification;

  @override
  DateTime fecha;

  @override
  List<UserNotification> userNotification;
  @override
  String evento;
  @override
  String typeNotification;
  @override
  List<String> channel;
  @override
  String title;
  @override
  String body;
  @override
  Map<String, ColumnMetaModel>? metaModel;
  NotifyModel({
    required this.id,
    required this.idNotification,
    required this.fecha,
    required this.userNotification,
    required this.evento,
    required this.typeNotification,
    required this.channel,
    required this.title,
    required this.body,
  }) : super(
          id: id,
          idNotification: idNotification,
          fecha: fecha,
          userNotification: userNotification,
          evento: evento,
          typeNotification: typeNotification,
          channel: channel,
          title: title,
          body: body,
        );
  factory NotifyModel.fromEmpty() => NotifyModel.fromJson({});
  factory NotifyModel.fromJson(Map<String, dynamic> json) => NotifyModel(
        id: EntityModel.getValueFromJson("id", json, "empty"),
        idNotification:
            EntityModel.getValueFromJson("idNotification", json, ""),
        fecha: EntityModel.getValueFromJson("fecha", json, DateTime.now()),
        userNotification:
            EntityModel.getValueFromJson("userNotification", json, []),
        evento: EntityModel.getValueFromJson("evento", json, ""),
        typeNotification:
            EntityModel.getValueFromJson("typeNotification", json, ""),
        channel: EntityModel.getValueFromJson("channel", json, []),
        title: EntityModel.getValueFromJson("title", json, ""),
        body: EntityModel.getValueFromJson("body", json, ""),
      );

  factory NotifyModel.fromXml(
          XmlElement element, NotifyModel Function(XmlElement el) process) =>
      process(element);

  @override
  Map<String, ColumnMetaModel>? get getMetaModel => getColumnMetaModel();

  List<Object?> get props => [];
  @override
  set setMetaModel(Map<String, ColumnMetaModel> newMetaModel) {
    metaModel = newMetaModel;
  }

  bool? get stringify => true;

  //method generated by wizard
  @override
  T cloneWith<T extends EntityModel>(T other) {
    return NotifyModel.fromJson(other.toJson()) as T;
  }

  @override
  EntityModelList createModelListFrom(dynamic data) {
    try {
      if (data is Map) {
        return NotifyList.fromJson(data as Map<String, dynamic>);
      }
      if (data is String) {
        return NotifyList.fromStringJson(data);
      }
    } on Exception {
      log("Error al mapear el parámetro 'data'. Debe ser de tipo'Map<String, dynamic>' o String");
    }
    return NotifyList.fromJson({});
  }

  @override
  T fromJson<T extends EntityModel>(Map<String, dynamic> params) {
    return NotifyModel.fromJson(params) as T;
  }

  @override
  Map<String, ColumnMetaModel> getColumnMetaModel() {
    ////Map<String, String> colNames = getColumnNames();
    metaModel = metaModel ??
        {
          //TODO Declare here all ColumnMetaModel. you can use class implementation of class "DefaultColumnMetaModel".
        };
    int index = 0;
    metaModel!.forEach((key, value) {
      value.setColumnIndex(index++);
    });
    return metaModel!;
  }

  @override
  Map<String, String> getColumnNames() {
    return {"id_notify": "ID"};
  }

  @override
  List<String> getColumnNamesList() {
    return getColumnNames().values.toList();
  }

  StreamController<EntityModel> getController({
    void Function()? onListen,
    void Function()? onPause,
    void Function()? onResume,
    FutureOr<void> Function()? onCancel,
  }) {
    return EntityModel.getController(
      entity: this,
      onListen: onListen,
      onPause: onPause,
      onResume: onResume,
      onCancel: onCancel,
    );
  }

  @override
  Map<K1, V1> getMeta<K1, V1>(String searchKey, dynamic searchValue) {
    final Map<K1, V1> result = {};
    getColumnMetaModel().map<K1, V1>((key, value) {
      MapEntry<K1, V1> el = MapEntry(value.getDataIndex() as K1, value as V1);
      if (value[searchKey] == searchValue) {
        result.putIfAbsent(value.getDataIndex() as K1, () {
          return value as V1;
        });
      }
      return el;
    });
    return result;
  }

  @override
  Map<String, String> getVisibleColumnNames() {
    Map<String, String> names = {};
    getMeta<String, ColumnMetaModel>("visible", true)
        .map<String, String>((key, value) {
      names.putIfAbsent(key, () => value.getColumnName());
      return MapEntry(key, value.getColumnName());
    });
    return names;
    // throw UnimplementedError();
  }

  @override
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['id'] = id;
    data['id_notification'] = idNotification;
    data['fecha'] = fecha;
    data['user_notification'] = userNotification
        .map((v) => (v as UserNotificationModel).toJson())
        .toList();
    data['evento'] = evento;
    data['type_notification'] = typeNotification;
    data['channel'] = channel;
    data['title'] = title;
    data['body'] = body;
    return data;
  }

  @override
  Map<String, ColumnMetaModel> updateColumnMetaModel(
      String keySearch, dynamic valueSearch, dynamic newValue) {
    Map<String, ColumnMetaModel> tmp = getColumnMetaModel();
    getMeta<String, ColumnMetaModel>(keySearch, valueSearch)
        .map<String, ColumnMetaModel>((key, value) {
      tmp.putIfAbsent(key, () => value);
      return MapEntry(key, value);
    });
    return metaModel = tmp;
  }

  @override
  static T? getValueFrom<T>(
      String key, Map<dynamic, dynamic> json, dynamic defaultValue) {
    if (defaultValue != null && defaultValue is ServerException) {
      throw defaultValue;
    }
    try {
      return EntityModel.getValueFromJson<T?>(key, json, defaultValue);
    } on Exception {
      throw CastErrorException();
    }
  }
}
