// To parse this JSON data, do
//
//     final userModel = userModelFromJson(jsonString);
// ignore_for_file: overridden_fields, empty_catches, override_on_non_overriding_member

import 'dart:async';
import 'dart:convert';
import 'dart:developer';

import 'package:xml/xml.dart';

import '../../../../../app/core/config/errors/exceptions.dart';
import '../../../../../app/core/interfaces/entity_model.dart';
import '../entities/user_notification.dart';

UserNotificationList user_notificationListModelFromJson(String str) =>
    UserNotificationList.fromJson(json.decode(str));

UserNotificationModel user_notificationModelFromJson(String str) =>
    UserNotificationModel.fromJson(json.decode(str));

String user_notificationModelToJson(UserNotificationModel data) =>
    json.encode(data.toJson());

class UserNotificationList<T extends UserNotificationModel>
    implements EntityModelList<T> {
  final List<T> user_notifications;

  UserNotificationList({
    required this.user_notifications,
  });

  factory UserNotificationList.fromJson(Map<String, dynamic> json) =>
      UserNotificationList(
        user_notifications: List<T>.from(json["user_notifications"]
            .map((x) => UserNotificationModel.fromJson(x))),
      );

  factory UserNotificationList.fromStringJson(String strJson) =>
      UserNotificationList.fromJson(json.decode(strJson));

  @override
  int get getTotal => getList().length;

  @override
  EntityModelList<T> add(T element) => fromList([element]);

  @override
  EntityModelList<T> fromJson(Map<String, dynamic> json) {
    return UserNotificationList.fromJson(json);
  }

  @override
  EntityModelList<T> fromList(List<T> list) {
    for (var element in list) {
      if (!user_notifications.contains(element)) {
        user_notifications.add(element);
      }
    }
    return this;
  }

  @override
  EntityModelList<T> fromStringJson(String strJson) {
    return UserNotificationList.fromStringJson(strJson);
  }

  @override
  List<T> getList() => user_notifications;

  Map<String, dynamic> toJson() => {
        "user_notifications":
            List<dynamic>.from(user_notifications.map((x) => x.toJson())),
      };

  static Future<T> fromXmlServiceUrl<T>(
      String url,
      String parentTagName,
      Future<T> Function(XmlDocument doc, XmlElement el) process,
      Future<T> Function() onError) async {
    return EntityModelList.fromXmlServiceUrl(
        url, parentTagName, process, onError);
  }

  static Future<T> getJsonFromXMLUrl<T>(
      String url,
      Future<T> Function(XmlDocument result) process,
      Future<T> Function() onError) async {
    return EntityModelList.getJsonFromXMLUrl(url, process, onError);
  }
}

class UserNotificationModel extends UserNotification implements EntityModel {
  @override
  String username;

  @override
  String phone;

  @override
  String email;

  @override
  Map<String, ColumnMetaModel>? metaModel;
  UserNotificationModel({
    required this.username,
    required this.phone,
    required this.email,
  }) : super(
          username: username,
          phone: phone,
          email: email,
        );
  factory UserNotificationModel.fromJson(Map<String, dynamic> json) =>
      UserNotificationModel(
        username: EntityModel.getValueFromJson("userName", json, ""),
        phone: EntityModel.getValueFromJson("phone", json, ""),
        email: EntityModel.getValueFromJson("email", json, ""),
      );
  factory UserNotificationModel.fromXml(XmlElement element,
          UserNotificationModel Function(XmlElement el) process) =>
      process(element);

  @override
  Map<String, ColumnMetaModel>? get getMetaModel => getColumnMetaModel();

  List<Object?> get props => [];

  @override
  set setMetaModel(Map<String, ColumnMetaModel> newMetaModel) {
    metaModel = newMetaModel;
  }

  bool? get stringify => true;

  //method generated by wizard
  @override
  T cloneWith<T extends EntityModel>(T other) {
    return UserNotificationModel.fromJson(other.toJson()) as T;
  }

  @override
  EntityModelList createModelListFrom(dynamic data) {
    try {
      if (data is Map) {
        return UserNotificationList.fromJson(data as Map<String, dynamic>);
      }
      if (data is String) {
        return UserNotificationList.fromStringJson(data);
      }
    } on Exception {
      log("Error al mapear el parámetro 'data'. Debe ser de tipo'Map<String, dynamic>' o String");
    }
    return UserNotificationList.fromJson({});
  }

  @override
  T fromJson<T extends EntityModel>(Map<String, dynamic> params) {
    return UserNotificationModel.fromJson(params) as T;
  }

  @override
  Map<String, ColumnMetaModel> getColumnMetaModel() {
    ////Map<String, String> colNames = getColumnNames();
    metaModel = metaModel ??
        {
          //TODO Declare here all ColumnMetaModel. you can use class implementation of class "DefaultColumnMetaModel".
        };
    int index = 0;
    metaModel!.forEach((key, value) {
      value.setColumnIndex(index++);
    });
    return metaModel!;
  }

  @override
  Map<String, String> getColumnNames() {
    return {"id_user_notification": "ID"};
  }

  @override
  List<String> getColumnNamesList() {
    return getColumnNames().values.toList();
  }

  StreamController<EntityModel> getController({
    void Function()? onListen,
    void Function()? onPause,
    void Function()? onResume,
    FutureOr<void> Function()? onCancel,
  }) {
    return EntityModel.getController(
      entity: this,
      onListen: onListen,
      onPause: onPause,
      onResume: onResume,
      onCancel: onCancel,
    );
  }

  @override
  Map<K1, V1> getMeta<K1, V1>(String searchKey, dynamic searchValue) {
    final Map<K1, V1> result = {};
    getColumnMetaModel().map<K1, V1>((key, value) {
      MapEntry<K1, V1> el = MapEntry(value.getDataIndex() as K1, value as V1);
      if (value[searchKey] == searchValue) {
        result.putIfAbsent(value.getDataIndex() as K1, () {
          return value as V1;
        });
      }
      return el;
    });
    return result;
  }

  @override
  Map<String, String> getVisibleColumnNames() {
    Map<String, String> names = {};
    getMeta<String, ColumnMetaModel>("visible", true)
        .map<String, String>((key, value) {
      names.putIfAbsent(key, () => value.getColumnName());
      return MapEntry(key, value.getColumnName());
    });
    return names;
    // throw UnimplementedError();
  }

  @override
  Map<String, dynamic> toJson() =>
      {"userName": username, "phone": phone, "email": email};

  @override
  Map<String, ColumnMetaModel> updateColumnMetaModel(
      String keySearch, dynamic valueSearch, dynamic newValue) {
    Map<String, ColumnMetaModel> tmp = getColumnMetaModel();
    getMeta<String, ColumnMetaModel>(keySearch, valueSearch)
        .map<String, ColumnMetaModel>((key, value) {
      tmp.putIfAbsent(key, () => value);
      return MapEntry(key, value);
    });
    return metaModel = tmp;
  }

  @override
  static T? getValueFrom<T>(
      String key, Map<dynamic, dynamic> json, dynamic defaultValue) {
    if (defaultValue != null && defaultValue is ServerException) {
      throw defaultValue;
    }
    try {
      return EntityModel.getValueFromJson<T?>(key, json, defaultValue);
    } on Exception {
      throw CastErrorException();
    }
  }
}
