// ignore_for_file: public_member_api_docs, sort_constructors_first
class MerchantPayment {
  String name;
  String alias;
  String code;
  String avatar;
  String contactCode;
  String receiveCode;
  String appId;
  String appName;
  String nit;
  String merchantUuid;
  String merchanName;
  String merchantAlias;
  String merchantAvatar;
  String merchantOpId;
  String transactionUuid;
  String statusCode;
  String statusDenom;
  String transactionCreated;
  String transactionUpdated;
  String transactionSignature;
  String leaf;
  String amount;
  String refundedAmount;
  String currency;
  String transactionDescription;
  String transactionDenom;
  String transactionCode;
  String comission;
  String terminalId;
  String invoiceNumber;
  String userName;
  String lastName;
  String items;
  String invoiceService;
  String verified;
  String userUuid;
  MerchantPayment({
    required this.name,
    required this.alias,
    required this.code,
    required this.avatar,
    required this.contactCode,
    required this.receiveCode,
    required this.appId,
    required this.appName,
    required this.nit,
    required this.merchantUuid,
    required this.merchanName,
    required this.merchantAlias,
    required this.merchantAvatar,
    required this.merchantOpId,
    required this.transactionUuid,
    required this.statusCode,
    required this.statusDenom,
    required this.transactionCreated,
    required this.transactionUpdated,
    required this.transactionSignature,
    required this.leaf,
    required this.amount,
    required this.refundedAmount,
    required this.currency,
    required this.transactionDescription,
    required this.transactionDenom,
    required this.transactionCode,
    required this.comission,
    required this.terminalId,
    required this.invoiceNumber,
    required this.userName,
    required this.lastName,
    required this.items,
    required this.invoiceService,
    required this.verified,
    required this.userUuid,
  });
}
